DepartmanProjesi/Models/Context.cs
using Microsoft.EntityFrameworkCore;

namespace DepartmanProjesi.Models
{
    public class Context:DbContext
    {
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer("server=DESKTOP-99SLPDA\\SQLEXPRESS; database=departmandb; integrated security=true; TrustServerCertificate=True;");
        }

        public DbSet<departmanlar> departmanlars { get; set; }
        public DbSet<personel> personels { get; set; }
    }
}

DepartmanProjesi/Models/ErrorViewModel.cs
namespace DepartmanProjesi.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DepartmanProjesi/Models/departmanlar.cs
using System.ComponentModel.DataAnnotations;

namespace DepartmanProjesi.Models
{
    public class departmanlar
    {
        [Key]
        public int id { get; set; }
        public string departmanad { get; set; }

        public List<personel> personels { get; set; }
    }
}

DepartmanProjesi/Models/personel.cs
using System.ComponentModel.DataAnnotations;

namespace DepartmanProjesi.Models
{
    public class personel
    {
        [Key]
        public int personelid { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public string sehir { get; set; }
        public departmanlar depart { get; set; }
    }
}

DepartmanProjesi/Controllers/HomeController.cs
using DepartmanProjesi.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace DepartmanProjesi.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DepartmanProjesi/Controllers/departController.cs
using Microsoft.AspNetCore.Mvc;
using DepartmanProjesi.Models;
namespace DepartmanProjesi.Controllers
{
    public class departController : Controller
    {
        Context c = new Context();
        public IActionResult Index()
        {
            var degerler = c.departmanlars.ToList();
            return View(degerler);
        }
        [HttpGet]
        public IActionResult YeniDepartman()
        {
            return View();
        }
        [HttpPost]
        public IActionResult YeniDepartman(departmanlar d)
        {
            c.departmanlars.Add(d);
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult DepartmanSil(int id)
        {
            var dep = c.departmanlars.Find(id);
            c.departmanlars.Remove(dep);
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        public IActionResult DepartmanGetir(int id)
        {
            var depart = c.departmanlars.Find(id);
            return View("DepartmanGetir",depart);
        }
        public IActionResult DepartmanGuncelle(departmanlar d)
        {
            var dep = c.departmanlars.Find(d.id);
            dep.departmanad = d.departmanad;
            c.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

DepartmanProjesi/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

DepartmanProjesi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DepartmanProjesi</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DepartmanProjesi.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DepartmanProjesi</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - DepartmanProjesi - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

DepartmanProjesi/Views/Shared/_TestLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<title>W3.CSS</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
<body>

    <!-- Sidebar -->
    <div class="w3-sidebar w3-light-grey w3-bar-block" style="width:15%">
        <h3 class="w3-bar-item">Menü</h3>
        <a href="/depart/Index/" class="w3-bar-item w3-button">Departmanlar</a>
        <a href="#" class="w3-bar-item w3-button">Personeller</a>
        <a href="#" class="w3-bar-item w3-button">Hakkımızda</a>
        <a href="#" class="w3-bar-item w3-button">Çıkış</a>
    </div>

    <!-- Page Content -->
    <div style="margin-left:15%">

        <div class="w3-container w3-teal">
            <h1>ASP.NET CORE MVC PROJESİ</h1>
        </div>

        <div class="w3-container">
            @RenderBody()
        </div>

    </div>

</body>
</html>

DepartmanProjesi/Views/depart/DepartmanGetir.cshtml
@model DepartmanProjesi.Models.departmanlar
@{
    ViewData["Title"] = "DepartmanGetir";
    Layout = "~/Views/Shared/_TestLayout.cshtml";
}
<br />
@using (Html.BeginForm("DepartmanGuncelle", "depart", FormMethod.Post))
{
    <b>Departman ID</b>
    @Html.TextBoxFor(x => x.id, new { @class = "form-control" })
    <br />

    <b>Departman Adı</b>
    @Html.TextBoxFor(x => x.departmanad, new { @class = "form-control" })
    <br />

    <button class="btn btn-info">Departman Güncelle</button>
}

DepartmanProjesi/Views/depart/Index.cshtml
@using DepartmanProjesi.Models
@model List<departmanlar>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_TestLayout.cshtml";
}

<br />
<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>Departman</th>
        <th>Sil</th>
        <th>Güncelle</th>
        <th>Detaylar</th>
    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <td>@x.id</td>
            <td>@x.departmanad</td>
            <td><a href="/depart/DepartmanSil/@x.id" class="btn btn-danger">Sil</a></td>
            <td><a href="/depart/DepartmanGetir/@x.id" class="btn btn-success">Güncelle</a></td>
            <td><a href="#" class="btn btn-outline-success" style="background-color:#e9f6f6">Detaylar</a></td>
        </tr>
    }

</table>
<a href="/depart/YeniDepartman" class="btn btn-primary">Yeni Departman Ekle</a>

DepartmanProjesi/Views/depart/YeniDepartman.cshtml
@model DepartmanProjesi.Models.departmanlar
@{
    ViewData["Title"] = "YeniDepartman";
    Layout = "~/Views/Shared/_TestLayout.cshtml";
}
<br />
<form class="form-group" method="post">
    

    <b>Departman Adı</b>
    @Html.TextBoxFor(x => x.departmanad, new { @class = "form-control" })
    <br />

    <button class="btn btn-info">Departman Ekle</button>

</form>